import Head from 'next/head';
// import Image from 'next/image'
// import styles from '../styles/Home.module.css';
import Layout from '../components/layouts/default';

export async function getServerSideProps() {
  // TODO: graphql the data
  return {
    props: {}, // will be passed to the page component as props
  };
}

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Layout>
  );
}
